import { writeFileSync } from 'fs'
import { join } from 'path'

import { readFile, WorkSheet } from 'xlsx'

/**
 * The PRM TABLE sheet lists the values of parameters that are an index into a
 * table rather than a number. Each table is introduced by a marker in column A
 * and lays its entries out over six value/data column pairs.
 */
const workbook = readFile(join(__dirname, 'source.xlsx'))
const worksheet = workbook.Sheets['PRM TABLE']

const columnPairs = [
  ['B', 'C'],
  ['D', 'E'],
  ['F', 'G'],
  ['H', 'I'],
  ['J', 'K'],
  ['L', 'M'],
]

const maxRow = 2000

function findTableRow(worksheet: WorkSheet, marker: string): number {
  for (let row = 1; row < maxRow; row++) {
    if (worksheet['A' + row]?.v === marker) return row
  }
  throw new Error(`${marker} not found`)
}

interface TableEntry {
  value: number
  data: string
}

function readTable(marker: string): TableEntry[] {
  const markerRow = findTableRow(worksheet, marker)
  const entries: TableEntry[] = []

  // the marker row is followed by a header row, then the entries
  for (let row = markerRow + 2; row < maxRow; row++) {
    // the next table's marker ends this one
    if (worksheet['A' + row]?.v) break

    for (const [valueColumn, dataColumn] of columnPairs) {
      const value = worksheet[valueColumn + row]?.v
      const data = worksheet[dataColumn + row]?.v
      if (typeof value !== 'number' || data === undefined) continue
      entries.push({ value, data: String(data) })
    }
  }

  return entries.sort((a, b) => a.value - b.value)
}

/**
 * The console displays Q values with one decimal from 1.0 up and two below,
 * which is also how the source formats them where they are strings.
 */
function formatQ(q: number): string {
  return q.toFixed(q >= 1 ? 1 : 2)
}

/** the Q values that select a filter instead of a bandwidth */
const qFilters: Record<string, { label: string; filter: string }> = {
  'Low Shelving': { label: 'L.SHELF', filter: 'lowShelf' },
  'High Shelving': { label: 'H.SHELF', filter: 'highShelf' },
  LPF: { label: 'LPF', filter: 'lowPass' },
  HPF: { label: 'HPF', filter: 'highPass' },
}

function qOption({ value, data }: TableEntry): string {
  const filter = qFilters[data]
  if (filter) {
    return `{ value: ${value}, label: '${filter.label}', filter: '${filter.filter}' }`
  }

  const q = parseFloat(data)
  return `{ value: ${value}, label: '${formatQ(q)}', number: ${q} }`
}

function frequencyOption({ value, data }: TableEntry): string {
  const hertz = data.endsWith('kHz')
    ? parseFloat(data) * 1000
    : parseFloat(data)
  return `{ value: ${value}, label: '${data}', number: ${hertz} }`
}

function optionsConstant(
  name: string,
  entries: TableEntry[],
  format: (entry: TableEntry) => string
): string {
  return `export const ${name}: DeviceEnumParameterOption[] = [
${entries.map(entry => `  ${format(entry)},`).join('\n')}
]`
}

const content = `import { DeviceEnumParameterOption } from '@remote-mixer/types'

// Generated by shared/scripts/src/yamaha-01v96/generate-eq-tables.ts
// PRM TABLE #11 and #12 of the parameter change list — do not edit by hand.

${optionsConstant('eqQOptions', readTable('PRM TABLE #11'), qOption)}

${optionsConstant(
  'eqFrequencyOptions',
  readTable('PRM TABLE #12'),
  frequencyOption
)}
`

writeFileSync(
  join(__dirname, '../../../../backend/src/devices/yamaha-01v96/eq-tables.ts'),
  content
)
